name: One Mace
main: com.xanemi.onemace.OneMacePlugin
version: 1.0
api-version: "1.21"
description: "Only one Mace can be crafted on the server."

commands:
  givemace:
    description: Give yourself the One Mace (only if none has been crafted)
    usage: /givemace
    permission: onemace.give

permissions:
  onemace.give:
    description: Allows giving the Mace
    default: op
